# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        runtime: [osx-arm64, osx-x64, linux-x64, win-x64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependancies
        run: dotnet restore -r ${{ matrix.runtime }} Fushigi/Fushigi.sln

      - name: Build
        run: dotnet build -c Release --no-restore Fushigi/Fushigi.sln

      - name: Publish
        run: dotnet publish -c Release -r ${{ matrix.runtime }} --no-restore Fushigi/Fushigi.sln

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.runtime }}
          path: Fushigi/bin/Release/net8.0/${{ matrix.runtime }}/publish
